name: Deployment

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    name: Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout is not needed: https://github.com/marketplace/actions/build-and-push-docker-images#usage
      - # https://github.com/marketplace/actions/docker-setup-qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - # https://github.com/marketplace/actions/docker-setup-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - # https://github.com/marketplace/actions/docker-login
        name: Login to Github docker repo
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - # Image for Latest and openjdk17.
        name: Build and Push Java 17
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/arian8j2/papermc:latest
          platforms: linux/amd64,linux/arm64
          build-args: JAVA_VERSION=openjdk17-jre-headless
          cache-from: type=registry,ref=ghcr.io/arian8j2/papermc:openjdk17
          cache-to: type=inline
